version: '3'
services:
  redis1:
    hostname: redis1
    container_name: redis1
    image: redis
    ports: 
      - "6301:6379"
      - "16301:16379"
    env_file:
      - ./env/ip.env
    volumes: 
      - "./node1/data:/data"
      - "./node1/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
  redis2:
    hostname: redis2
    container_name: redis2
    image: redis
    ports: 
      - "6302:6379"
      - "16302:16379"
    env_file:
      - ./env/ip.env
    volumes: 
      - "./node2/data:/data"
      - "./node2/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
  redis3:
    hostname: redis3
    container_name: redis3
    image: redis
    ports: 
      - "6303:6379"
      - "16303:16379"
    env_file:
      - ./env/ip.env
    volumes: 
      - "./node3/data:/data"
      - "./node3/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
  redis4:
    hostname: redis4
    container_name: redis4
    image: redis
    ports: 
      - "6304:6379"
      - "16304:16379"
    env_file:
      - ./env/ip.env
    volumes: 
      - "./node4/data:/data"
      - "./node4/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
  redis5:
    hostname: redis5
    container_name: redis5
    image: redis
    ports: 
      - "6305:6379"
      - "16305:16379"
    env_file:
      - ./env/ip.env
    volumes: 
      - "./node5/data:/data"
      - "./node5/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
  redis6:
    hostname: redis6
    container_name: redis6
    image: redis
    ports: 
      - "6306:6379"
      - "16306:16379"
    env_file:
      - ./env/ip.env
    volumes: 
      - "./node6/data:/data"
      - "./node6/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf