version: "3"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:latest
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    env_file:
      - ./env/nacos-hostname.env
    restart: always
    depends_on:
      - nacos-mysql
  nacos2:
    hostname: nacos2
    container_name: nacos2
    image: nacos/nacos-server:latest
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8849:8848"
    env_file:
      - ./env/nacos-hostname.env
    restart: always
    depends_on:
      - nacos-mysql  
  nacos3:
    hostname: nacos3
    container_name: nacos3
    image: nacos/nacos-server:latest
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8850:8848"
    env_file:
      - ./env/nacos-hostname.env
    restart: always
    depends_on:
      - nacos-mysql  
  nacos-mysql:
    container_name: nacos-mysql
    image: nacos/nacos-mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  nacos-nginx:
    container_name: nacos-nginx
    build: ./nginx
    ports: 
      - "8888:80"
    volumes: 
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    restart: always