version: 3
services:
  nacos:
    image: paderlol/nacos:latest
      container_name: nacos-standalone
      environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      volumes:
      - ./logs:/home/nacos/logs
      ports:
      - "8848:8848"
    