version: '3.8'
services:
  rocketmq-nameserver:
    hostname: rocketmq-nameserver
    container_name: rocketmq-nameserver
    image: apacherocketmq/rocketmq
    ports:
      - 9876:9876
    volumes:
      - ./nameserver/logs:/home/rocketmq/logs
    command: sh mqnamesrv
  rocketmq-console:
    hostname: rocketmq-console
    container_name: rocketmq-console
    image: apacherocketmq/rocketmq-console:2.0.0
    ports: 
      - 11000:8080
    environment:
      - "JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmq-nameserver:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rocketmq-nameserver
  rocketmq-broker-m1:
    hostname: rocketmq-broker-m1
    container_name: rocketmq-broker-m1
    image: apacherocketmq/rocketmq
    ports:
      - 11909:10909
      - 11911:11911
      - 11912:10912
    volumes:
      - ./broker-m1/logs:/home/rocketmq/logs
      - ./broker-m1/store:/home/rocketmq/store
      - ./broker-m1/conf/broker.conf:/opt/rocketmq-ROCKETMQ_VERSION/conf/broker.conf
    command: sh mqbroker -n rocketmq-nameserver:9876 -c /opt/rocketmq-ROCKETMQ_VERSION/conf/broker.conf
    depends_on:
      - rocketmq-nameserver
  rocketmq-broker-s1:
    hostname: rocketmq-broker-s1
    container_name: rocketmq-broker-s1
    image: apacherocketmq/rocketmq
    ports:
      - 12909:10909
      - 12911:12911
      - 12912:10912
    volumes:
      - ./broker-s1/logs:/home/rocketmq/logs
      - ./broker-s1/store:/home/rocketmq/store
      - ./broker-s1/conf/broker.conf:/opt/rocketmq-ROCKETMQ_VERSION/conf/broker.conf
    command: sh mqbroker -n rocketmq-nameserver:9876 -c /opt/rocketmq-ROCKETMQ_VERSION/conf/broker.conf
    depends_on:
      - rocketmq-nameserver
  rocketmq-broker-m2:
    hostname: rocketmq-broker-m2
    container_name: rocketmq-broker-m2
    image: apacherocketmq/rocketmq
    ports:
      - 13909:10909
      - 13911:13911
      - 13912:10912
    volumes:
      - ./broker-m2/logs:/home/rocketmq/logs
      - ./broker-m2/store:/home/rocketmq/store
      - ./broker-m2/conf/broker.conf:/opt/rocketmq-ROCKETMQ_VERSION/conf/broker.conf
    command: sh mqbroker -n rocketmq-nameserver:9876 -c /opt/rocketmq-ROCKETMQ_VERSION/conf/broker.conf
    depends_on:
      - rocketmq-nameserver
  rocketmq-broker-s2:
    hostname: rocketmq-broker-s2
    container_name: rocketmq-broker-s2
    image: apacherocketmq/rocketmq
    ports:
      - 14909:10909
      - 14911:14911
      - 14912:10912
    volumes:
      - ./broker-s2/logs:/home/rocketmq/logs
      - ./broker-s2/store:/home/rocketmq/store
      - ./broker-s2/conf/broker.conf:/opt/rocketmq-ROCKETMQ_VERSION/conf/broker.conf
    command: sh mqbroker -n rocketmq-nameserver:9876 -c /opt/rocketmq-ROCKETMQ_VERSION/conf/broker.conf
    depends_on:
      - rocketmq-nameserver